# Import the libraries and dataset

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'C:\Users\Anshul Singh\Downloads\hackerearth\Machine Leaning contest\Pet adoption\Dataset\train.csv')
df.head()


pet_id           issue_date         listing_date  condition  \
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00        2.0   
1  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00        1.0   
2  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00        NaN   
3  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00        1.0   
4  ANSL_57969  2017-09-28 00:00:00  2017-11-19 09:38:00        2.0   

    color_type  length(m)  height(cm)  X1  X2  breed_category  pet_category  
0  Brown Tabby       0.80        7.78  13   9             0.0             1  
1        White       0.72       14.19  13   9             0.0             2  
2        Brown       0.15       40.90  15   4             2.0             4  
3        White       0.62       17.82   0   1             0.0             2  
4        Black       0.50       11.06  18   4             0.0             1

# Feature engineering on date coloumn

In [2]:
from datetime import date
sd = df.iloc[:,1:2].values
ld = df.iloc[:,2:3].values

days = []
for i in range(len(sd)):
    y1,m1,d1 = (sd[i][0][:10]).split("-")
    y2,m2,d2 = (ld[i][0][:10]).split("-")
    f_date = date(int(y1),int(m1),int(d1))
    l_date = date(int(y2),int(m2),int(d2))
    delta = l_date - f_date
    days.append(delta.days)
#print(days)


# Add another coloumn into dataset (days)

In [3]:
df.insert(3, 'days', days)
df.head()

pet_id           issue_date         listing_date  days  condition  \
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00    73        2.0   
1  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00  1862        1.0   
2  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00   752        NaN   
3  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00   755        1.0   
4  ANSL_57969  2017-09-28 00:00:00  2017-11-19 09:38:00    52        2.0   

    color_type  length(m)  height(cm)  X1  X2  breed_category  pet_category  
0  Brown Tabby       0.80        7.78  13   9             0.0             1  
1        White       0.72       14.19  13   9             0.0             2  
2        Brown       0.15       40.90  15   4             2.0             4  
3        White       0.62       17.82   0   1             0.0             2  
4        Black       0.50       11.06  18   4             0.0             1

# Convert colortype(string) to integer

In [4]:
df["color_type"] = df["color_type"].astype('category')
df["color_type"] = df["color_type"].cat.codes
df.head()

pet_id           issue_date         listing_date  days  condition  \
0  ANSL_69903  2016-07-10 00:00:00  2016-09-21 16:25:00    73        2.0   
1  ANSL_66892  2013-11-21 00:00:00  2018-12-27 17:47:00  1862        1.0   
2  ANSL_69750  2014-09-28 00:00:00  2016-10-19 08:24:00   752        NaN   
3  ANSL_71623  2016-12-31 00:00:00  2019-01-25 18:30:00   755        1.0   
4  ANSL_57969  2017-09-28 00:00:00  2017-11-19 09:38:00    52        2.0   

   color_type  length(m)  height(cm)  X1  X2  breed_category  pet_category  
0          18       0.80        7.78  13   9             0.0             1  
1          53       0.72       14.19  13   9             0.0             2  
2          15       0.15       40.90  15   4             2.0             4  
3          53       0.62       17.82   0   1             0.0             2  
4           2       0.50       11.06  18   4             0.0             1

# Checking outliers

In [5]:
max1 = df['pet_category'].quantile(0.999)
print(max1)
min1 = df['pet_category'].quantile(0.001)
min1

4.0


0.0

In [6]:
df.shape

(18834, 12)

In [7]:
df.describe()

days     condition    color_type     length(m)    height(cm)  \
count  18834.000000  17357.000000  18834.000000  18834.000000  18834.000000   
mean     855.306786      0.883390     24.560529      0.502636     27.448832   
std     1096.674990      0.770434     19.432010      0.288705     13.019781   
min      -76.000000      0.000000      0.000000      0.000000      5.000000   
25%      119.000000      0.000000      4.000000      0.250000     16.172500   
50%      392.000000      1.000000     18.000000      0.500000     27.340000   
75%     1117.000000      1.000000     48.000000      0.760000     38.890000   
max     8056.000000      2.000000     55.000000      1.000000     50.000000   

                 X1            X2  breed_category  pet_category  
count  18834.000000  18834.000000    18834.000000  18834.000000  
mean       5.369598      4.577307        0.600563      1.709143  
std        6.572366      3.517763        0.629883      0.717919  
min        0.000000      0.000000        0.000000      0.000000  
25%        0.000000      1.000000        0.000000      1.000000  
50%        0.000000      4.000000        1.000000      2.000000  
75%       13.000000      9.000000        1.000000      2.000000  
max       19.000000      9.000000        2.000000      4.000000

# Removing outliers

In [8]:
df = df[(df['pet_category']<max1) & (df['pet_category']>min1)]

In [9]:
df.shape

(17805, 12)

In [10]:
df.describe()

days     condition    color_type     length(m)    height(cm)  \
count  17805.000000  17162.000000  17805.000000  17805.000000  17805.000000   
mean     876.356922      0.875656     24.756585      0.501980     27.430845   
std     1120.019191      0.767267     19.588715      0.288512     13.018868   
min      -76.000000      0.000000      0.000000      0.000000      5.000000   
25%      116.000000      0.000000      3.000000      0.250000     16.160000   
50%      394.000000      1.000000     18.000000      0.500000     27.290000   
75%     1120.000000      1.000000     48.000000      0.750000     38.880000   
max     8056.000000      2.000000     55.000000      1.000000     50.000000   

                 X1            X2  breed_category  pet_category  
count  17805.000000  17805.000000    17805.000000  17805.000000  
mean       4.997529      4.598427        0.536984      1.596518  
std        6.402922      3.583666        0.566460      0.490610  
min        0.000000      0.000000        0.000000      1.000000  
25%        0.000000      1.000000        0.000000      1.000000  
50%        0.000000      4.000000        1.000000      2.000000  
75%       13.000000      9.000000        1.000000      2.000000  
max       19.000000      9.000000        2.000000      2.000000

# Defining dependent and independent variables for breed category

In [11]:
bX = df.iloc[:,3:-2].values
by = df.iloc[:,-2:-1].values

# Handle missing values

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(bX)
bX = imputer.transform(bX)
bX

array([[7.300e+01, 2.000e+00, 1.800e+01, ..., 7.780e+00, 1.300e+01,
        9.000e+00],
       [1.862e+03, 1.000e+00, 5.300e+01, ..., 1.419e+01, 1.300e+01,
        9.000e+00],
       [7.550e+02, 1.000e+00, 5.300e+01, ..., 1.782e+01, 0.000e+00,
        1.000e+00],
       ...,
       [2.954e+03, 0.000e+00, 2.200e+01, ..., 2.813e+01, 1.300e+01,
        9.000e+00],
       [2.720e+02, 0.000e+00, 4.800e+01, ..., 4.482e+01, 1.300e+01,
        9.000e+00],
       [2.509e+03, 0.000e+00, 1.500e+01, ..., 3.740e+01, 0.000e+00,
        1.000e+00]])

# Feature scaling

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(bX)

StandardScaler(copy=True, with_mean=True, with_std=True)

# Defining dependent and independent variables for pet category

In [14]:
pX = df.iloc[:,3:-1].values
py = df.iloc[:,-1:].values

In [15]:
# Handle Missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(pX)
pX = imputer.transform(pX)
pX

array([[7.300e+01, 2.000e+00, 1.800e+01, ..., 1.300e+01, 9.000e+00,
        0.000e+00],
       [1.862e+03, 1.000e+00, 5.300e+01, ..., 1.300e+01, 9.000e+00,
        0.000e+00],
       [7.550e+02, 1.000e+00, 5.300e+01, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [2.954e+03, 0.000e+00, 2.200e+01, ..., 1.300e+01, 9.000e+00,
        1.000e+00],
       [2.720e+02, 0.000e+00, 4.800e+01, ..., 1.300e+01, 9.000e+00,
        1.000e+00],
       [2.509e+03, 0.000e+00, 1.500e+01, ..., 0.000e+00, 1.000e+00,
        1.000e+00]])

In [16]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(pX)

StandardScaler(copy=True, with_mean=True, with_std=True)

# Train the model for breed category

In [17]:
from xgboost import XGBClassifier
from sklearn.ensemble import BaggingClassifier
breed = XGBClassifier().fit(bX, by)

C:\Users\Anshul Singh\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
C:\Users\Anshul Singh\Anaconda3\lib\site-packages\distributed\config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
C:\Users\Anshul Singh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Anshul Singh\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of

# Train the model for Pet category

In [18]:
pet = XGBClassifier().fit(pX, py)

In [19]:
# Extract date feature (Feature engineering)

tf = pd.read_csv(r'C:\Users\Anshul Singh\Downloads\hackerearth\Machine Leaning contest\Pet adoption\Dataset\test.csv')
from datetime import date
sd = tf.iloc[:,1:2].values
ld = tf.iloc[:,2:3].values

days = []
for i in range(len(sd)):
    y1,m1,d1 = (sd[i][0][:10]).split("-")
    y2,m2,d2 = (ld[i][0][:10]).split("-")
    f_date = date(int(y1),int(m1),int(d1))
    l_date = date(int(y2),int(m2),int(d2))
    delta = l_date - f_date
    days.append(delta.days)

tf.insert(3, 'days', days)
tf["color_type"] = tf["color_type"].astype('category')
tf["color_type"] = tf["color_type"].cat.codes
tf.head()

pet_id           issue_date         listing_date  days  condition  \
0  ANSL_75005  2005-08-17 00:00:00  2017-09-07 15:35:00  4404        0.0   
1  ANSL_76663  2018-11-15 00:00:00  2019-05-08 17:24:00   174        1.0   
2  ANSL_58259  2012-10-11 00:00:00  2018-04-02 16:51:00  1999        1.0   
3  ANSL_67171  2015-02-13 00:00:00  2018-04-06 07:25:00  1148        1.0   
4  ANSL_72871  2017-01-18 00:00:00  2018-04-26 13:42:00   463        1.0   

   color_type  length(m)  height(cm)  X1  X2  
0           2       0.87       42.73   0   7  
1          36       0.06        6.71   0   1  
2           2       0.24       41.21   0   7  
3           2       0.29        8.46   7   1  
4          14       0.71       30.92   0   7

# Taking input for breed categroy model

In [20]:
btest = tf.iloc[:,3:].values
tf.head()

pet_id           issue_date         listing_date  days  condition  \
0  ANSL_75005  2005-08-17 00:00:00  2017-09-07 15:35:00  4404        0.0   
1  ANSL_76663  2018-11-15 00:00:00  2019-05-08 17:24:00   174        1.0   
2  ANSL_58259  2012-10-11 00:00:00  2018-04-02 16:51:00  1999        1.0   
3  ANSL_67171  2015-02-13 00:00:00  2018-04-06 07:25:00  1148        1.0   
4  ANSL_72871  2017-01-18 00:00:00  2018-04-26 13:42:00   463        1.0   

   color_type  length(m)  height(cm)  X1  X2  
0           2       0.87       42.73   0   7  
1          36       0.06        6.71   0   1  
2           2       0.24       41.21   0   7  
3           2       0.29        8.46   7   1  
4          14       0.71       30.92   0   7

In [21]:
#Handle missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(btest)
btest = imputer.transform(btest)

In [22]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(btest)

StandardScaler(copy=True, with_mean=True, with_std=True)

# Predict result for breed categry

In [23]:
y_breed = breed.predict(btest)
y_breed

array([1., 0., 0., ..., 1., 2., 1.])

In [24]:
tf1 = tf

In [25]:
tf1['breed_category'] = y_breed
tf1.head()

pet_id           issue_date         listing_date  days  condition  \
0  ANSL_75005  2005-08-17 00:00:00  2017-09-07 15:35:00  4404        0.0   
1  ANSL_76663  2018-11-15 00:00:00  2019-05-08 17:24:00   174        1.0   
2  ANSL_58259  2012-10-11 00:00:00  2018-04-02 16:51:00  1999        1.0   
3  ANSL_67171  2015-02-13 00:00:00  2018-04-06 07:25:00  1148        1.0   
4  ANSL_72871  2017-01-18 00:00:00  2018-04-26 13:42:00   463        1.0   

   color_type  length(m)  height(cm)  X1  X2  breed_category  
0           2       0.87       42.73   0   7             1.0  
1          36       0.06        6.71   0   1             0.0  
2           2       0.24       41.21   0   7             0.0  
3           2       0.29        8.46   7   1             0.0  
4          14       0.71       30.92   0   7             0.0

In [26]:
#taking ip for pet category
ptest = tf1.iloc[:,3:].values

In [27]:
#Handle missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(ptest)
ptest = imputer.transform(ptest)

In [28]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(ptest)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [29]:
#Predict result for pet categry

In [30]:
y_pet = pet.predict(ptest)
y_pet

array([2, 1, 2, ..., 2, 2, 2], dtype=int64)

# Store it into a csv file

In [32]:
pet_id = tf.iloc[:,:1].values
Pet1 = pd.DataFrame(pet_id)
Pet1['breed_category'] = y_breed
Pet1['pet_category'] = y_pet
Pet1.columns = ['pet_id','breed_category','pet_category']
Pet1.to_csv('Main2.csv',index=False)